google/codemirror.dart

.gitignore
README.md
UPDATING_CODEMIRROR.md
changelog.md
lib/codemirror.dart
pubspec.yaml
tool/drone.sh
tool/grind.dart

rev 0.1.4; add modes

---

changelog.md
example/simple.css
example/simple.dart
example/simple.html
lib/codemirror.dart
lib/hints.dart
pubspec.yaml

In progress PR to add a code completion API. The sync version is working; the async version has issues.

working on code completion

---

lib/codemirror.dart

Added replaceSelection method to Doc class. http://codemirror.net/doc/manual.html#replaceSelection

Added replaceSelection method

---

lib/codemirror.dart

Added replaceRange method in Doc class. http://codemirror.net/doc/manual.html#replaceRange

Added replaceRange method

---

example/simple.dart

Fixed typo in sample

---

AUTHORS
changelog.md
lib/codemirror.dart
pubspec.yaml

@xxgreg, can you verify the AUTHORS info?

0.2.1+5.0.0

---

changelog.md
example/simple.dart
pubspec.yaml
third_party/codemirror/addon/hint/show-hint.js

Devoncarew code completion patch

---

AUTHORS
changelog.md
example/simple.dart
lib/hints.dart
pubspec.yaml

@kasperpeulen 
- tweak how we expose the hints shown and close events
- prep for releasing the next version

registerOnShown, registerOnClose

---

lib/codemirror.dart

Ensure object identity for `CodeMirror` instances that point to the same JS codemirror instance.

ensure object identity

---

changelog.md
example/simple.dart
lib/hints.dart
pubspec.yaml

- document and tweak how we expose the hints `select` and `pick` events
- prep for new release
@kasperpeulen

expose hints select, pick

---

changelog.md
pubspec.yaml
third_party/codemirror/addon/hint/show-hint.js

rev codemirror to capture a bug fix

---

changelog.md
lib/codemirror.dart
test/all.dart

create a dart 'Mode' object

---

changelog.md
lib/codemirror.dart
lib/hints.dart
pubspec.yaml
tool/travis.sh

- fix https://github.com/google/codemirror.dart/issues/47
- make ddc (strong mode) compliant

strong mode

---

lib/codemirror.dart

https://github.com/google/codemirror.dart/issues/50
Found with the `warning` logging level in DDC.

more strong mode

---

changelog.md
example/simple.dart
lib/hints.dart
tool/travis.sh

fix https://github.com/google/codemirror.dart/issues/54

fix async code completer

---

changelog.md

With a fancy improved Dart mode:

tweak changelog

---

lib/codemirror.dart

Add `Span.hashCode`

---

changelog.md
lib/codemirror.dart
test/all_test.dart

There are some more useful selection related methods which may be worth exposing.

Expose methods for adding and extending selections.

---

lib/codemirror.dart

change a List type to Map

---

.travis.yml
analysis_options.yaml
example/simple.dart
lib/codemirror.dart
lib/hints.dart
lib/src/js_utils.dart
pubspec.yaml
test/all_test.dart
tool/grind.dart
tool/travis.sh

Tested with DartPad and passes unit tests, now.

Make codemirror work at runtime with Dart 2.0.

---

changelog.md
pubspec.yaml

publish 0.4.5

---

changelog.md
lib/codemirror.dart
pubspec.yaml

- fix a bug in removeLineClass
- prep for 0.4.6

fix a bug in removeLineClass

---

changelog.md
lib/codemirror.dart
pubspec.yaml

- change the field types for the ScrollInfo class from int to num
- hopefully help to address https://github.com/flutter/devtools/issues/405
@domesticmouse

change the field types for the ScrollInfo class from int to num

---

AUTHORS
README.md
analysis_options.yaml
example/simple.dart
lib/codemirror.dart
lib/hints.dart
lib/panel.dart
lib/src/js_utils.dart
test/all_test.dart
tool/grind.dart

- Reduce verbosity of code by removing redundant "new" while calling constructors.
- format code.

Removes redundant "new" usage while calling constructors.

---

lib/codemirror.dart

Fixing https://travis-ci.org/google/codemirror.dart/builds/529085566
TBR @devoncarew

Code fix curly_braces_in_flow_control_structures

---

pubspec.yaml

Updating version

---

lib/codemirror.dart
lib/hints.dart
pubspec.yaml

removed dart:async

---

.github/workflows/dart.yml
CHANGELOG.md
README.md
analysis_options.yaml
example/simple.dart
lib/codemirror.dart
lib/hints.dart
lib/panel.dart
lib/src/js_utils.dart
test/all_test.dart
tool/grind.dart
updating_codemirror.md

Mostly around cleaning up some null safety usage. There is still more than can be done in the future, but this an okay start.
Closes https://github.com/google/codemirror.dart/issues/122

Misc cleanup and updates

---

CHANGELOG.md
pubspec.yaml

CodeMirror.dart 0.7.0 release

---

CHANGELOG.md
README_.google
pubspec.yaml
third_party/codemirror/AUTHORS
third_party/codemirror/CHANGELOG.md
third_party/codemirror/addon/merge/merge.js
third_party/codemirror/doc/manual.html
third_party/codemirror/doc/realworld.html
third_party/codemirror/doc/releases.html
third_party/codemirror/index.html
third_party/codemirror/lib/codemirror.js
third_party/codemirror/mode/clike/clike.js
third_party/codemirror/mode/groovy/groovy.js
third_party/codemirror/package.json
third_party/codemirror/src/edit/main.js
third_party/codemirror/src/line/spans.js
tool/grind.dart
tool/travis.sh

Update to CodeMirror 5.65.3

---

CHANGELOG.md
README_.google
pubspec.yaml
third_party/codemirror/AUTHORS
third_party/codemirror/CHANGELOG.md
third_party/codemirror/addon/hint/show-hint.css
third_party/codemirror/addon/hint/show-hint.js
third_party/codemirror/addon/hint/sql-hint.js
third_party/codemirror/addon/merge/merge.js
third_party/codemirror/doc/manual.html
third_party/codemirror/doc/releases.html
third_party/codemirror/index.html
third_party/codemirror/lib/codemirror.js
third_party/codemirror/mode/clike/clike.js
third_party/codemirror/mode/javascript/javascript.js
third_party/codemirror/mode/jinja2/index.html
third_party/codemirror/mode/jinja2/jinja2.js
third_party/codemirror/mode/nsis/nsis.js
third_party/codemirror/mode/pegjs/pegjs.js
third_party/codemirror/mode/sparql/sparql.js
third_party/codemirror/mode/sql/sql.js
third_party/codemirror/mode/swift/swift.js
third_party/codemirror/package.json
third_party/codemirror/src/display/Display.js
third_party/codemirror/src/edit/main.js
third_party/codemirror/src/input/ContentEditableInput.js
third_party/codemirror/src/input/TextareaInput.js
third_party/codemirror/src/input/input.js

Update to CodeMirror 5.65.11

---

CHANGELOG.md
README_.google
pubspec.yaml
third_party/codemirror/AUTHORS
third_party/codemirror/CHANGELOG.md
third_party/codemirror/LICENSE
third_party/codemirror/doc/manual.html
third_party/codemirror/doc/releases.html
third_party/codemirror/index.html
third_party/codemirror/lib/codemirror.js
third_party/codemirror/mode/python/python.js
third_party/codemirror/mode/python/test.js
third_party/codemirror/package.json
third_party/codemirror/src/edit/main.js
third_party/codemirror/theme/bespin.css

CodeMirror 5.65.12

---

README.md

Fix: https://github.com/google/codemirror.dart/issues/161

Mark this package as a Dart package, not a Flutter package.

---

CHANGELOG.md
pubspec.yaml
test/all_test.dart

This is a PR to upgrade the `web` dependency to `1.1.0`.

Upgrade web to 1.1.0

---

.github/dependabot.yaml
.github/workflows/dart.yml
analysis_options.yaml

- update the ci
- add a dependabot config
- ignore deprecated members

update ci; add dependabot config
